### ISSUE TITLE
Doesn't work for me - Better setup & testing instructions?

### ISSUE THREAD

**Issue by mborus** [pimoroni/PiratePython#12]
Thanks for building this, 
I'm looking forward to getting this to work.

Some feedback:

At the moment I made some guesses and formatted a SD card with FAT32 and then
copied the files (on windows 10).

On start, the pi zero W LED blinks 7-8 times quickly, the stays on lit half a second,
the repeats that again.

No drive showing up, 

I also tried on Ubuntu and looked at dmesg after connecting, nothing.
No output on the HDMI video out, no networks appearing, 
I currently have no way to check serial other than via usb,
so I'm guessing it doesn't work here.

BTW, please mention the python version this is loading...

**Comment by Gadgetoid** [comment]
It's *very* alpha, so these things will follow soon once we know where the gotchas are.

What size SD card were you using, and how did you format it?

**Comment by mborus** [comment]
8GB size (Samsung)
Formatted to FAT32 using windows10 (right click on drive letter, select format)
I downloaded the code as a zip and unzipped the "sdcard" folder onto the card
root. (I later checked the card on ubuntu and the card content looked OK)

Reg alpha status, I understand, that's why I posted some feedback.

**Comment by Gadgetoid** [comment]
The size of the ramdisk means it takes significantly longer than a second or two to load, meaning it might not fit your use-case well. It's closer to 30-40sec. Although, granted, it can be streaming internet radio in under a minute from a cold boot which isn't completely terrible.

You could play with the tooling to generate your own, smaller ramdisk with this goal in mind, however.

At the moment I'm focusing on Pi Zero since its ability to be mounted as a USB slave device is fairly key to the whole concept. There's no reason it couldn't support other Pi's in the form of alternate distributions, but I have no immediate plans to do so.

Finding ways to slim the ramdisk down to speed up boot times is on my todo list, unfortunately this is at odds with supporting multiple Pi versions with the same distribution.

I think Windows 10's formatting process is doing something that renders the card unreadable to the Pi. I've been using the- not especially brilliant- SDFormatter from here to prepare cards: https://www.sdcard.org/downloads/formatter_4/

**Comment by ali1234** [comment]
> Finding ways to slim the ramdisk down to speed up boot times is on my todo list, unfortunately this is at odds with supporting multiple Pi versions with the same distribution.

Almost all the support files for different revisions (kernel, device trees etc) should be outside the ramdisk. Only kernel modules should be duplicated inside it, and the only driver that needs to be a module is the wifi driver due to firmware loading.
